schema: 'queries/schema.docs.graphql'
documents: '**/*.graphql'
extensions:
  endpoints:
    GitHub:
      url: https://api.github.com/graphql
      headers:
        Authorization: bearer ${GITHUB_TOKEN}